---
- name: Set environment variables
  hosts: md-dagster
  vars_files:
    - ../terraform/ansible_vars_file.yml
  tasks:
    - name: Set BASIC_AUTH_USERNAME
      set_fact:
        BASIC_AUTH_USERNAME: "{{ lookup('env', 'BASIC_AUTH_USERNAME', default='dagster') }}"
    - name: Set BASIC_AUTH_PASSWORD
      set_fact:
        BASIC_AUTH_PASSWORD: "{{ lookup('env', 'BASIC_AUTH_PASSWORD', default='dagster') }}"
    - name: Set AWS_ACCESS_KEY_ID
      set_fact:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID', default='access_key') }}"
    - name: Set AWS_SECRET_ACCESS_KEY
      set_fact:
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY', default='secret_key') }}"
    - name: Set POSTGRES_PASSWORD
      set_fact:
        POSTGRES_PASSWORD: "{{ lookup('env', 'POSTGRES_PASSWORD', default='dagster') }}"
    # Add environment variables to /etc/profile
    - name: Add environment variables to /etc/profile
      become: true
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
        create: true
      loop:
        - "export BASIC_AUTH_USERNAME={{ BASIC_AUTH_USERNAME }}"
        - "export BASIC_AUTH_PASSWORD={{ BASIC_AUTH_PASSWORD }}"
        - "export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}"
        - "export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}"
        - "export POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}"
      no_log: true

