[project]
name = "meteo-data-exploratory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "polars>=1.19.0",
]
