output "dagster_public_ip" {
  value = upcloud_server.md-dagster.network_interface[0].ip_address
}

output "dagster_private_ip" {
  value = upcloud_server.md-dagster.network_interface[1].ip_address
}

output "object_storage_endpoint" {
  value = upcloud_managed_object_storage.md-object-storage.endpoint
}

output "object_storage_private_endpoint_domain_name" {
  value = tolist(upcloud_managed_object_storage.md-object-storage.endpoint)[0].domain_name
}

output "object_storage_public_endpoint_domain_name" {
  value = tolist(upcloud_managed_object_storage.md-object-storage.endpoint)[1].domain_name
}

output "object_storage_key_id" {
  value = upcloud_managed_object_storage_user_access_key.md-raw-data.access_key_id
}

output "object_storage_secret_access_key" {
  value     = upcloud_managed_object_storage_user_access_key.md-raw-data.secret_access_key
  sensitive = true
}

resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    dagster_ip: ${upcloud_server.md-dagster.network_interface[0].ip_address}
    dagster_private_ip: ${upcloud_server.md-dagster.network_interface[1].ip_address}
    object_storage_private_endpoint: https://${tolist(upcloud_managed_object_storage.md-object-storage.endpoint)[0].domain_name}
    object_storage_public_endpoint: https://${tolist(upcloud_managed_object_storage.md-object-storage.endpoint)[1].domain_name}
    object_storage_key_id: ${upcloud_managed_object_storage_user_access_key.md-raw-data.access_key_id}
    object_storage_secret_access_key: ${upcloud_managed_object_storage_user_access_key.md-raw-data.secret_access_key}
    DOC
  filename = "./ansible_vars_file.yml"
}
