name: 'Terraform Deploy'
# on: 
#   push:
#     branches:
#       - main
#     paths:
#       - infrastructure/terraform/**
#   workflow_dispatch:
on:
  workflow_call

env:
  UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
  UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ./infrastructure/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./infrastructure/.ssh/id_ed25519.pub
          chmod 644 ./infrastructure/.ssh/id_ed25519.pub
          ls -la ./infrastructure/.ssh

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: infrastructure/terraform
      
      - name: 'Terraform Format'
        run: terraform fmt -check
        working-directory: infrastructure/terraform

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: infrastructure/terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: infrastructure/terraform
