name: 'Terraform / Ansible Deploy'
# on: 
#   push:
#     branches:
#       - main
#     paths:
#       - infrastructure/terraform/**
#   workflow_dispatch:
on:
  workflow_call:
    inputs:
      run_ansible:
        type: boolean
        default: false
      run_terraform:
        type: boolean
        default: false

env:
  UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
  UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}

jobs:
  terraform-ansible:
    name: 'Terraform / Ansible'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ./infrastructure/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./infrastructure/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./infrastructure/.ssh/id_ed25519.pub
          chmod 600 ./infrastructure/.ssh/id_ed25519
          chmod 644 ./infrastructure/.ssh/id_ed25519.pub

      # - name: Install Ansible
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y ansible
      #   if: "${{ inputs.run_ansible }}"

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: 'Terraform Init'
        run: terraform init
        working-directory: infrastructure/terraform
      
      - name: 'Terraform Format'
        run: terraform fmt -check
        working-directory: infrastructure/terraform
        if: "${{ inputs.run_terraform }}"

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: infrastructure/terraform
        if: "${{ inputs.run_terraform }}"

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: infrastructure/terraform
        if: "${{ inputs.run_terraform }}"
      
      - name: Terraform Output
        run: |
          echo "DAGSTER_PRIVATE_IP=$(terraform output -raw dagster_private_ip)" > "$GITHUB_OUTPUT"
          echo "DAGSTER_PUBLIC_IP=$(terraform output -raw dagster_public_ip)" >> "$GITHUB_OUTPUT"
          echo "OBJECT_STORAGE_ENDPOINT=https://$(terraform output -raw object_storage_private_endpoint_domain_name)" >> "$GITHUB_OUTPUT"
          echo "OBJECT_STORAGE_KEY_ID=$(terraform output -raw object_storage_key_id)" >> "$GITHUB_OUTPUT"
          echo "OBJECT_STORAGE_SECRET_ACCESS_KEY=$(terraform output -raw object_storage_secret_access_key)" >> "$GITHUB_OUTPUT"
        working-directory: infrastructure/terraform

      - name: Run Ansible
        run: |
          ansible-playbook 01-ensure-docker.yml
        working-directory: infrastructure/ansible
        if: "${{ inputs.run_ansible }}"
       
