name: 'Ansible Deploy Docker'
on:
  workflow_call

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Set up SSH
        run |
          mkdir -p ~/infrastructure/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/infrastructure/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/infrastructure/.ssh/id_ed25519.pub
          chmod 600 ~/infrastructure/.ssh/id_ed25519
          chmod 644 ~/infrastructure/.ssh/id_ed25519.pub
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Run Ansible
        run: |
          ansible-playbook 01-ensure-docker.yml
        working-directory: infrastructure/ansible
