name: Run Dagster

on:
  workflow_call

jobs:
  dagster:
    name: Run Dagster w docker-compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ./infrastructure/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./infrastructure/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./infrastructure/.ssh/id_ed25519.pub
          chmod 600 ./infrastructure/.ssh/id_ed25519
          chmod 644 ./infrastructure/.ssh/id_ed25519.pub

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Ansible vars'
        run: |
          terraform apply -auto-approve -target=local_file.tf_ansible_vars_file_new
        working-directory: infrastructure/terraform

      - name: Run Ansible
        run: |
          ansible-playbook 02-copy-dagster.yml 03-run-dagster.yml
        working-directory: infrastructure/ansible
