name: 'Deploy All'
on:
  workflow_dispatch

jobs:
  terraform:
    uses: ./.github/workflows/01-deploy-infrastructure.yml
    secrets: inherit
    inputs:
      run_terraform: true
      run_ansible: true

  dagster:
    needs: terraform
    uses: ./.github/workflows/02-run-dagster.yml
    secrets: inherit
