name: 'Terraform Deploy'
on: 
  push:
    branches:
      - main
    paths:
    - infrastructure/terraform/**
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: infrastructure/terraform
      
      - name: 'Terraform Format'
        run: terraform fmt -check
        working-directory: infrastructure/terraform

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: infrastructure/terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: infrastructure/terraform
